apiVersion: v1
kind: Service
metadata:
  name: service-astroporfolio
  namespace: namespace-miportfolio
spec:
  type: NodePort
  selector:
    app: astroporfolio
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30086 # Puerto Ãºnico para tu proyecto Astro