services:
  build:
    build:
      context: ${CONTEXTO_RAIZ}
      dockerfile: dockerfiles/base/ubbase
      args:
        - PROYECTO=${PROYECTO}
        - USUARIO=${USUARIO}
        - TIPO=${TIPO}
        - USER_NAME=${USER_NAME}
        - USER_PASS=${USER_PASS}
        - PATH_SRC=${PATH_SRC} 
    image: ${DOCKER_USER}/${PROYECTO}:latest